### ISSUE TITLE
Are there any real sampled data from USRP

### ISSUE THREAD

**Issue by hitdshu** [yungshenglu/Simple_SISO_OFDM_USRP#1]
Dear David Lu,

Thanks for your repo. I'm studying OFDM recently. Instead of simulating using matlab, I'd like to see the OFDM receiver's performance in real IQ data. Are there any sampled data from USRP in your repos?

Best,
Deshun Hu

**Comment by hitdshu** [comment]
@yungshenglu

**Comment by davidyslu** [comment]
Hi @hitdshu,
Sorry for the late response. This repository is a lab of my course originally. Basically, I just keep one of the data from USRP in the folder `out/`. You can find the data there whether you need. Thanks.

Best,
David Lu

**Comment by hitdshu** [comment]
Hi @yungshenglu ,

Thanks for your reply. I found one USRP data in your folder out as you said. I'll check it later. Thanks.
